apiVersion: v1
kind: Pod

metadata:
  name: pod-teste
  namespace: desafio-kubernetes
  labels:
    app: pod-teste

spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80