apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: desafio-kubernetes

type: Opaque

stringData:
  POSTGRES_USER: desafio_user
  POSTGRES_PASSWORD: SUA_SENHA_FORTE
  PGRST_DB_URI: postgres://desafio_user:SUA_SENHA_URL_ENCODED@postgres:5432/desafio_db